# PRACTICA 5

In [1]:
import numpy as np

### 1)

In [2]:
# Uso que A=L+D+U
A = np.array([[3,1,1],[-2,4,1],[1,1,-3]])
b = np.array([5,3,-1])
print(np.triu(A))
print(np.triu(A,1))#esta es la que sirve para U, los numeros de la diagonal deben estar debajo de 1
print(np.tril(A))
print(np.tril(A,-1))#esta es la que sirve para L, los numeros de la diagonal deben estar arriba de -1
print(np.diag(A))
print(np.diag(np.diag(A))) #esta es la que sirve para D 

[[ 3  1  1]
 [ 0  4  1]
 [ 0  0 -3]]
[[0 1 1]
 [0 0 1]
 [0 0 0]]
[[ 3  0  0]
 [-2  4  0]
 [ 1  1 -3]]
[[ 0  0  0]
 [-2  0  0]
 [ 1  1  0]]
[ 3  4 -3]
[[ 3  0  0]
 [ 0  4  0]
 [ 0  0 -3]]


In [3]:
def Jacobi(A,b,tol=1e-10,m=100,x0=[]): # Elegimos una tolerancia para nuestro error y un máximo de 100 iteraciones
    n    = A.shape[0]
    d    = np.diag(A)
    invD = np.diag(1/d)     # Es la inversa de D
    LU    = np.tril(A,-1)+np.triu(A,1)
    T   = -invD@LU           # Matriz de iteraciones de Jacobi
    c    = invD@b
    if len(x0) == 0:        # Si no se ingresa un vector inicial, le damos un vector inicial aleatorio  
        x = np.random.random(n)
    else:
        x = x0

    xold = np.zeros(n)       
    i=0
    print("Radio espectral:", max(abs(np.linalg.eig(T)[0])))
    print(x)
    while np.linalg.norm(x-xold)>tol and i<m: 
        xold=x.copy()      #### SIEMPRE USAR COPY PARA VECTORES Y MATRICES
        x = T@xold + c
        print(x)
        i=i+1
        if i==m:
            print('ATENCIÓN: se alcanzó el número máximo de iteraciones')
    return x,i-1           ### pido el vector solución y la cantidad de iteraciones realizadas

In [4]:
def GaussSeidel(A,b,tol=1e-10,m=100,x0=[]):
    n = A.shape[0]
    d = np.diag(np.diag(A))
    L = np.tril(A,-1)
    U = np.triu(A,1)
    DL = d + L
    invDL = np.linalg.inv((DL))
    T = -invDL@U
    c = invDL@b
    if len(x0) == 0:        # Si no se ingresa un vector inicial, le damos un vector inicial aleatorio  
        x = np.random.random(n)
    else:
        x = x0
    
    xold = np.zeros(n)
    i = 0
    print("Radio espectral:", max(abs(np.linalg.eig(T)[0])))
    print(x)
    while np.linalg.norm(x-xold)>tol and i<m: 
        xold=x.copy()      #### SIEMPRE USAR COPY PARA VECTORES Y MATRICES
        x = T@xold + c
        print(x)
        i=i+1
        if i==m:
            print('ATENCIÓN: se alcanzó el número máximo de iteraciones')
    return x,i-1           ### pido el vector solución y la cantidad de iteraciones realizadas

### 4)

In [5]:
#A)

A = np.array([[3,1,1],[2,6,1],[1,1,4]])
b = np.array([5,9,6])

print(np.linalg.solve(A,b))
print(Jacobi(A,b))
print(GaussSeidel(A,b))

[1. 1. 1.]
Radio espectral: 0.5575346466519526
[0.39651024 0.713427   0.74623092]
[1.18011403 1.2434581  1.22251569]
[0.8446754  0.90287604 0.89410697]
[1.06767233 1.0694237  1.06311214]
[0.95582139 0.96692387 0.96572599]
[1.02245005 1.02043854 1.01931369]
[0.98674926 0.9892977  0.98927785]
[1.00714148 1.00620394 1.00598826]
[0.99593593 0.99662146 0.99666365]
[1.0022383  1.00191075 1.00186065]
[0.99874287 0.99894379 0.99896274]
[1.00069782 1.00059192 1.00057834]
[0.99960991 0.999671   0.99967756]
[1.00021714 1.00018377 1.00017977]
[0.99987882 0.99989766 0.99989977]
[1.00006752 1.0000571  1.00005588]
[0.99996234 0.99996818 0.99996884]
[1.00002099 1.00001775 1.00001737]
[0.99998829 0.99999011 0.99999032]
[1.00000653 1.00000552 1.0000054 ]
[0.99999636 0.99999692 0.99999699]
[1.00000203 1.00000171 1.00000168]
[0.99999887 0.99999904 0.99999906]
[1.00000063 1.00000053 1.00000052]
[0.99999965 0.9999997  0.99999971]
[1.0000002  1.00000017 1.00000016]
[0.99999989 0.99999991 0.99999991]
[1.00000

[5.36363637 0.90909089 4.0909091 ]
